# Generated by Django 4.2.6 on 2025-02-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultausuario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto'),
        ),
    ]
